/*
* WRITTEN BY SARGIS S YONAN ON 24 NOVEMBER 2015
* HEADER DEFINITIONS FOR A COMMANDS LIBRARY
* USED FOR A MICRO GRID TEST BED PROJECT
* GITHUB.COM/SARGISYONAN
*/


// LIST OF ALL POSSIBLE BINARY TRANSMISSION CODES

// SUCCESS/ERROR CODES //
#ifndef COMMANDS_H
#define COMMANDS_H



#define PROCESS_COMMAND_SUCCESS					0x0001
#define CORRUPT_PACKET_TRANSMISSION				0x00FA
#define PROCESS_COMMAND_ERROR					0x0000
#define CHANGE_SETPOINT_ERROR_CODE				0x00F0
#define TRANSMISSION_ERROR_CODE					0x00F1	// sent if message was too large or too small in length
#define CHANGE_POSITIVE_OFFSET_ERROR_CODE		0x00F2
#define CHANGE_NEGATIVE_OFFSET_ERROR_CODE		0x00F4
#define UNKNOWN_ERROR_CODE						0x00F8

/////////////////////////

// RX/TX COMMANDS //

#define SYSTEM_INITIALIZED						0x0011
#define ENABLE_STATE_MACHINE					0x00FF
#define DISABLE_STATE_MACHINE					0x0000
#define RECEIVE_MESSAGE_CHANGE_SETPOINT			0x0001
#define RECEIVE_MESSAGE_CHANGE_POSITIVE_OFFSET	0x0002
#define RECEIVE_MESSAGE_CHANGE_NEGATIVE_OFFSET	0x0004
#define RECEIVE_MESSAGE_GET_SYSTEM_STATUS		0x0008

////////////////////

#endif